### ISSUE TITLE
给你提个issue，看看能不能发出去

### ISSUE THREAD

**Issue by brohan1705** [Liby-web/liboyu62346-gmail.com#1]
<div person>
  <h2 name>xxx</h2>
  <p wanna>Web前端, 4年, 西安</p>
  <p>📱123-456-789 | 📧123@456.com</p>
</div>
<h3 line>技能</h3>
  <span yahei>精通JavaScript、Html、CSS，熟悉前端框架框架Vue、AngularJs、JQueryUI，熟悉CSS预处理语言Less，熟悉服务端开发语言java、node.js, 熟悉版本控制工具Git</span>
<h3 line>教育经历</h3>
<div>
  <div bold left>西安交通大学, 硕士</div>
  <div italic right>2013.9 - 2016.6</div>
</div>
<div>
  <div bold left>西安交通大学, 本科</div>
  <div italic right>2009.9 - 2013.6</div>
</div>
<h3 line>工作经历</h3>
<div>
  <div left>华为技术有限公司, 前端开发</div>
  <div italic right>2016 - 至今</div>
</div>
<h3 line>项目经历</h3>
<div>
  <div bold left><b>自研组件库sxxxt-ui-pro</b></div>
  <div yahei left><i>组件负责人</i></div>
  <div italic right>2019.11 - 至今</div>
  <p kaiti>
    sxxxt-ui-pro是基于vue框架的前端自研组件库，是sxxxt-ui自研组件库的vue版本，提供了大量基础组件及业务常用的高级组件。
    <br>
    <b>个人职责:</b>组件库切vue过程中的技术选型、工程配置、组件设计、组件开发、前端性能优化、前端安全分析，并对接业务在组件使用过程中遇到的问题、对业务开发中的难点提供技术支持。维护组件API平台，通过markdown自动生成
    <br>
    <b>技术栈：</b> JavaScript、Html、CSS、vue、vue-cli、less、jest、eslint
  </p>
  <div bold left><b>自研组件库sxxxt-ui</b></div>
  <div yahei left><i>组件负责人</i></div>
  <div italic right>2019.3 - 至今</div>
  <p kaiti>
    sxxxt-ui是基于JqueryUI框架的前端自研组件库，提供了大量基础组件及业务常用的高级组件。
    <br>
    <b>个人职责:</b> 组件设计、组件开发、 前端性能优化、前端安全分析，并对接业务在组件使用过程中遇到的问题、对业务开发中的难点提供技术支持。
    <br>
    <b>技术栈：</b> JavaScript、Html、CSS、JQueryUI、RequireJs、Echarts
  </p>
  <div bold left><b>FusionCloud私有云解决方案 租户管理系统</b></div>
  <div yahei left><i>模块设计 & 前端开发</i></div>
  <div italic right>2017.8 - 2019.2</div>
  <p kaiti>
    租户管理系统提供对私有云平台租户内用户、角色、项目、资源配额的管理能力。
    <br>
      <b>个人职责:</b>模块设计、 前端开发、 前端性能优化、 前端安全分析。
    <br>
      <b>技术栈：</b> JavaScript、Html、CSS、SVG、AngularJs、RequireJs、UnderScore、 Echarts
  </p>
  <div bold left><b>FusionCloud私有云解决方案 私有云门户Console Home</b></div>
  <div yahei left><i>前端开发</i></div>
  <div italic right>2016.9 - 2017.8</div>
  <p kaiti>
    Console Home是FusionC华为私有云解决方案的门户页面，包含了公告、待办、账户信息、产品列表、资源列表等信息。
    <br>
    <b>个人职责:</b>前端页面开发。
    <br>
    <b>技术栈：</b> JavaScript、Html、CSS、SVG、AngularJs、RequireJs、UnderScore
  </p>
</div>

**Comment by Liby-web** [comment]
优秀！
